
# Parameters for evaluaton

  eval_paths:                          # --- parent key, DO NOT FILL this line 

    eval_folders:                      # --- parent key, DO NOT FILL this line 
 
        parentfolder:                  # Path to the parent folder that will be used as root to other subfolders. Ex: "/data/evaluate_scchvn/" [str]
 
        instancemap_subfolder:         # Path to the subfolder (relative to parent folder) containing numpy instance maps from SCC Hovernet tile prediction. Ex: "/instancemaps/" [str] 

        classvector_subfolder:         # Path to the subfolder (relative to parent folder) containing numpy class vectors from SCC Hovernet tile prediction. Ex: "/instancetypes/" [str] 

        prediction_subfolder:          # Path to the subfolder (relative to parent folder) containing numpy class maps from SCC Hovernet tile prediction. Ex: "/instancetypes/classmaps/" [str]

        gt_subfolder:                  # Path to the subfolder (relative to parent folder) containing groundtruth labels in 5D numpy Hovernet format (see NucSeg dataset description). Ex: /trainingset/validation/labels/ [str]

        save_folder:                   # Absolute path to the folder to save evaluation results. Ex: "/data/evaluate_scchvn/results/" [str]
         

# All none strings parameters

  parameters:                          # --- parent key, DO NOT FILL this line 

    int:                               # --- parent key, DO NOT FILL this line 

      nbr_classes: 5                   # Number of cell classes predicted by SCC Hovernet. Default: 5 [int]

    bool:                              # --- parent key, DO NOT FILL this line 

      calculate_pq: True               # Calculate or not panoptic quality. Default: True [bool]
     
      calculate_confusion: True        # Calculate or not confusion matrix. Default: True [bool]
    
      create_classmap: True            # Generate or not class map from class vector output of Hovernet. Default: True [bool]
       
