

# parameter for evaluaton
  eval_paths:
    eval_folders:
        parentfolder: "/data/lsancere/Data_General/TrainingSets/Hovernet/Carina-Corinna-Johannes-Data/\
        ChrisSeg-LucasJohannesUpdatesClass/Hvn-Mc-annotations/NapariClassCorrection/TrainingDataGeneration/"
      
        instancemap_subfolder: '/InfonVal_output/mat/InstancesMaps/'

        classvector_subfolder: '/InfonVal_output/mat/InstancesTypes/'

        prediction_subfolder:  '/InfonVal_output/mat/InstancesTypes/ClassMaps/'

        gt_subfolder: '/TrainingSet/Val/Labels/'

        save_folder: '/data/lsancere/Data_General/Evaluations/Evaluation_Hovernet/'
         

# All not strings parameters
  parameters:

    int:
      nbr_classes: 5
      #number of cell classes 

    bool:
      calculate_pq: False 
      # Calculate or not panoptic quality

      calculate_confusion: True 
      # Calculate or not confusion matrix

      create_classmap: False
      # Generate class map from class vector output of Hovernet 
