
# Parameters for inference:

  inference:

    hovernet_mode: wsi

    gpulist: "0,1"

    paths:
      
      checkpoints: "/data/lsancere/checkpoints_temp/hvn_bestweights.tar"

      input_dir: "/data/shared/scc/progress/Cologne/"

      output_dir: "/data/shared/scc/hovernet_prediction/opt4set5extended_wsimode/test/"

      cache_path: "/dev/shm/cachelucas/"





# Parameters for training?
