
# Parameters for inference:

  inference:

    paths:
      
      checkpoints_dir: ""

      input_dir: ""

      output_dir: ""

      cache_path: ""


    gpulist: '0,1'


    hovernet_mode: wsi



# Parameters for training?