
# Parameters for inference:

  inference:

    hovernet_mode: wsi

    gpulist: "0,1"

    paths:
      
      checkpoints: "/data/lsancere/bestcheckpoints-histo-miner/hvn_bestweights.tar"

      input_dir: "/data/lsancere/Data_General/Collaborators_Dataset/cSCC_CPI/"

      output_dir: "/data//lsancere/Data_General/Collaborators_Dataset/cSCC_CPI_hvnoutput/"
      
      cache_path: "/dev/shm/cachelucas/"



# Parameters for training?
