
# Parameters for inference:

  inference:

    hovernet_mode: wsi

    gpulist: "0,1"

    paths:
      
      checkpoints: "/data/lsancere/bestcheckpoints-histo-miner/hvn_bestweights.tar"

      input_dir: "/data/lsancere/Data_General/Collaborators_Dataset/cSCC_CPI_all/\
      cSCC_CPI_extra_folders/cSCC_CPI_extra3/"
      # "/data/lsancere/Data_General/TrainingSets/Hovernet/Carina-Corinna-Johannes-Data/\
      # ChrisSeg-LucasJohannesUpdatesClass/Hvn-Mc-annotations/NapariClassCorrection/\
      # TrainingDataGeneration/TrainingSet/Val/Images/"

      output_dir: "/data/lsancere/Data_General/Collaborators_Dataset/cSCC_CPI_all/\
      cSCC_CPI_extra_folders/cSCC_CPI_extra3_hvnoutput/"
      # "/data/lsancere/Data_General/TrainingSets/Hovernet/Carina-Corinna-Johannes-Data/\
      # ChrisSeg-LucasJohannesUpdatesClass/Hvn-Mc-annotations/NapariClassCorrection/\
      # TrainingDataGeneration/TrainingSet/Val/InfonVal_output/"
      
      cache_path: "/dev/shm/cache-histominer/"



# Parameters for training?
