# Parameters for inference:

  inference:

    downsample_needed: True

    gpu: 1

    samples_per_gpu: 1 
    
    workers_per_gpu: 8 

    paths:

      checkpoints: "/data/lsancere/bestcheckpoints-histo-miner/segmenter_bestweights.pth"

      input_dir: "/data/lsancere/Data_General/Collaborators_Dataset/cSCC_CPI/"

      output_dir: "/data/lsancere/Data_General/Collaborators_Dataset/cSCC_CPI_segmenteroutput/"

  


# Parameters for training?

## All the parameters inside schedule could be added here 
