# Parameters for inference:

  inference:

    downsample_needed: "true"
    # !boolean in bash is without capital!

    gpu: 2

    samples_per_gpu: 1 
    
    workers_per_gpu: 8 

    paths:

      checkpoints: "/data/lsancere/Data_General/Weights/bestcheckpoints-histo-miner/sccsegmenter_bestweights.pth"

      input_dir:  "/data/lsancere/Data_General/Collaborators_Dataset/cSCC_CPI_all/\
      cSCC_CPI_Bonn/Bonn/"

      output_dir: "/data/lsancere/Data_General/Collaborators_Dataset/cSCC_CPI_all/\
      cSCC_CPI_Bonn/Bonn_segmenteroutput/"

     


    # SLURM PARAMETERS 
    # run_on_slurm: "true" 
    # boolean in bash is without capital

    # slurm_param:
    #   # to know name of partititon and have more info run:
    #   # sinfo -N -r -l
    #   # on SLURM
    #   partition: debug

    #   job_name: seginf


# Parameters for training?

## All the parameters inside schedule could be added here 
