
# All path related parameters
# the "" quotes allow to break the line with \ properly for then loading into python
  paths:
    folders:
        main: "/home/lsancere/These/CMMC/Ada_Mount/lsancere/Data_General/histo-miner/\
        testdataorga/test-featureselection/"



# All parameters of string names





# All not strings parameters

  parameters:
    int:
      nbr_keptfeat: 5