
# All path related parameters
# the "" quotes allow to break the line with \ properly for then loading into python
  paths:
    folders:
        main: "/home/lsancere/These/CMMC/Ada_Mount/lsancere/Data_General/\
        histo-miner/testdataorga/recurrence/Dortmund(copy)"


# All parameters of string names
  names:
      hovernet_mode: wsi

      managment:
        # For some reason, >- is needed because if not we will have an issue with the quotes inside the string
        str2replace_tilemode: >-
           {"mag": null, "nuc": {

        newstr_tilemode: >-
           {

        str2replace2_tilemode: >-
           }}}

        newstr2_tilemode: >-
           }}

        str2replace_wsimode: >-
          {"mag": 40, "nuc": {

        newstr_wsimode: >-
          {

        str2replace2_wsimode: >-
          }}}

        newstr2_wsimode: >-
          }}


# All not strings parameters
  parameters:

    lists:
      selectedclasses: [1, 2, 3, 4, 5]

      classnames: ['Granulocyte', 'Lymphocyte' , 'Plasme', 'Stroma', 'Tumor']

      classnames_injson:  ['"type": 0', '"type": 1', '"type": 2', '"type": 3', '"type": 4', '"type": 5']

      values2change: [1, 2]

      newvalues: [0, 255]

    int:
      maskmap_downfactor: 32



