
# All path related parameters
# the "" quotes allow to break the line with \ properly for then loading into python
  paths:
    folders:
        main: "/home/lsancere/These/CMMC/Ada_Mount/lsancere/Data_General/histo-miner/testdataorga/tissue_analyses/"


# All not strings parameters
  parameters:
    bool:
      perform_split: True

      classification_from_allfeatures: True

      saving_classifiers:
        ridge: True

        logistic_regression: True

        random_forest: True
    int:
      split_pourcentage: 15


# Classifiers parameters

  classifierparam:
    ridge:
      # For more information on the parameters check sklearn.linear_model.RidgeClassifier documentation
      # #https://scikit-learn.org/stable/modules/linear_model.html
      alpha:  2

    logistic_regression:
      # For more information on the parameters check sklearn.linear_model.LogisticRegression documentation
      # #https://scikit-learn.org/stable/modules/linear_model.html
      solver: 'liblinear'

      multi_class: 'ovr'

    random_forest:
      # For more information on the parameters check sklearn.linear_model.RandomForestClassifier documentation
      # #https://scikit-learn.org/stable/modules/linear_model.html
      n_estimators: 100

      class_weight: 'balanced'












