
# All path related parameters
# the "" quotes allow to break the line with \ properly for then loading into python
  paths:
    folders:
        inferences_postproc_main: "/data/shared/scc/tissue_analyser/data_analysis/no_progress/Regensburg"
        tissue_analyser_main: "/data/shared/scc/tissue_analyser/data_analysis/"
        feature_selection_main: ""
#        main: "/home/lsancere/These/CMMC/Ada_Mount/lsancere/Data_General/histo-miner/testdataorga/tissue_analyses/"
        


# All parameters of string names
  names:
      hovernet_mode: wsi

      managment:
        # >- is needed because if not we will have an issue with the quotes inside the string
        str2replace_tilemode: >-
           {"mag": null, "nuc": {

        newstr_tilemode: >-
           {

        str2replace2_tilemode: >-
           }}}

        newstr2_tilemode: >-
           }}

        str2replace_wsimode: >-
          {"mag": 40, "nuc": {

        newstr_wsimode: >-
          {

        str2replace2_wsimode: >-
          }}}

        newstr2_wsimode: >-
          }}


# All not strings parameters
  parameters:
    lists:
      selectedcls_dist: [1, 2, 3, 5]
      # Selected Classes for the Distance Calculation (average closest distance between cells of given class)
      # For a very comprehensive (but wazy too long for now) analysis we can keep all classes:
      # [1, 2, 3, 4, 5, 6]
      # For a realistic analysis speed, avoid including stroma cells and epithelial cells
      # in the distance calculation and then keep:
      # [1, 2, 3, 5]

      selectedcls_ratio: [1, 2, 3, 4, 5]
      # Selected Classes for ratio calculcations inside tumor regions
      # COULD BE REDUCED TO ONLY ONE SELECTEDCLASS AS Stromal cell ratio inside tumor is not interesting and maybe
      # Missleadin

      classnames: ['Granulocyte', 'Lymphocyte' , 'Plasma', 'Stroma', 'Tumor', 'Epithelial']
      #Still to test when the analyser will run

      classnames_injson:  ['"type": 0', '"type": 1', '"type": 2', '"type": 3', '"type": 4', '"type": 5', '"type": 6']

      values2change: [1, 2]

      newvalues: [0, 255]

    int:
      maskmap_downfactor: 32

      nbr_keptfeat: 5

    bool:
      classification_from_allfeatures: True

    str:
      maskmap_ext: .png











