
# All path related parameters
# the "" quotes allow to break the line with \ properly for then loading into python
  paths:
    folders:
        main: "/data/shared/scc/histo-miner/data_analysis/"

        inferences_postproc_main: "/data/lsancere/Data_General/Collaborators_Dataset/cSCC_CPI_extra1_hvnoutput/"

        tissue_analyser_main: "/data/shared/scc/histo-miner/data_analysis/tissue_analyses_sorted_Bonn/no_recurrence/"
        # tissue_analyser_main: "/data/lsancere/Data_General/Collaborators_Dataset/cSCC_CPI_extra1_hvnoutput/"

        # feature_selection_main: "/data/shared/scc/histo-miner/data_analysis/feature_selection_selectedslides/"
        feature_selection_main: "/data/shared/scc/histo-miner/data_analysis/feature_selection/all_Cohorts_withlogs/"

        classification_evaluation: "/data/shared/scc/histo-miner/data_analysis/classification_evaluation/"

        visualizations: "/data/shared/scc/histo-miner/data_analysis/visualizations/"

        workingfolder: "/data/lsancere/Data_General/TrainingSets/Hovernet/Carina-Corinna-Johannes-Data/\
        ChrisSeg-LucasJohannesUpdatesClass/Hvn-Mc-annotations/NapariClassCorrection/TrainingDataGeneration/\
        TrainingSet/Val/"
      
        
    files:
      patientid_csv: "/data/shared/scc/histo-miner/data_analysis/crea_patient_ID_lst/AllCohorts_PatientIDs.csv"
      #it is including extension of the file as well (.csv)


# All parameters of string names
  names:
      hovernet_mode: wsi

      eval_folder: varfeat-one-class-lgbm-logs

      managment:
        # >- is needed because if not we will have an issue with the quotes inside the string
        str2replace_tilemode: >-
           {"mag": null, "nuc": {

        newstr_tilemode: >-
           {

        str2replace2_tilemode: >-
           }}}

        newstr2_tilemode: >-
           }}

        str2replace_wsimode: >-
          {"mag": 40, "nuc": {

        newstr_wsimode: >-
          {

        str2replace2_wsimode: >-
          }}}

        newstr2_wsimode: >-
          }}

      example_json: "no_recurrence/147_21_no_recurrence_analysed.json"


# All not strings parameters
  parameters:
    lists:
      selectedcls_dist: [1, 2, 3, 5]
      # Selected Classes for the Distance Calculation (average closest distance between cells of given class)
      # For a very comprehensive (but wazy too long for now) analysis we can keep all classes:
      # [1, 2, 3, 4, 5, 6]
      # For a realistic analysis speed, avoid including stroma cells and epithelial cells
      # in the distance calculation and then keep:
      # [1, 2, 3, 5]

      selectedcls_ratio: [1, 2, 3, 4, 5]
      # Selected Classes for ratio calculcations inside tumor regions
      # COULD BE REDUCED TO ONLY ONE SELECTEDCLASS AS Stromal cell ratio inside tumor is not interesting and maybe
      # Missleadin

      classnames: ['Granulocyte', 'Lymphocyte' , 'Plasma', 'Stroma', 'Tumor', 'Epithelial']
      #Still to test when the analyser will run

      classnames_injson:  ['"type": 0', '"type": 1', '"type": 2', '"type": 3', '"type": 4', '"type": 5', '"type": 6']

      values2change: [1, 2]

      newvalues: [0, 255]

    int:
      maskmap_downfactor: 32

      nbr_keptfeat: 56

      boruta_max_depth: 10
      # boruta_max_depth: 18 leading to best results so far
      # boruta_max_depth: (2, 4) 6, 8, 10, 12, 14, 16, 18, 20
      # parenthesis are for Boruta applied to selected slides 

      boruta_random_state: 1

    bool:
      calculate_distances: False 

      display_classification_predictions: False

      display_classification_scores: True

      patientid_avail: True
      
      perpatient_feat: False
      # Now this name is very missleading should be updated 

      wsi_selection: False
      # not sure it is needed so far

      permutation: True
      # use or not the permutation index for the HP seach of curriculum

      plot: 
        boxplots: True

        distributions: True 

        pca: True

        tsne: True

        delete_outliers: True 





    str:
      maskmap_ext: .png











