
# All path related parameters
# the "" quotes allow to break the line with \ properly for then loading into python
  paths:
    folders:
        main: "/home/lsancere/These/CMMC/Ada_Mount/lsancere/Data_General/histo-miner/testdataorga/tissue_analyses/"


# All parameters of string names
  names:
      hovernet_mode: wsi

      managment:
        # For some reason, >- is needed because if not we will have an issue with the quotes inside the string
        str2replace_tilemode: >-
           {"mag": null, "nuc": {

        newstr_tilemode: >-
           {

        str2replace2_tilemode: >-
           }}}

        newstr2_tilemode: >-
           }}

        str2replace_wsimode: >-
          {"mag": 40, "nuc": {

        newstr_wsimode: >-
          {

        str2replace2_wsimode: >-
          }}}

        newstr2_wsimode: >-
          }}


# All not strings parameters
  parameters:
    lists:
      selectedclasses: [1, 2, 3, 5]
      # For a very comprehensive (but wazy too long for now) analysis we can keep all classes:
      # [1, 2, 3, 4, 5]
      # For a realistic analysis speed, avoid including stroma cells in the distance calculation and then keep:
      # [1, 2, 3, 5]

      classnames: ['Granulocyte', 'Lymphocyte' , 'Plasme', 'Stroma', 'Tumor']

      classnames_injson:  ['"type": 0', '"type": 1', '"type": 2', '"type": 3', '"type": 4', '"type": 5']

      values2change: [1, 2]

      newvalues: [0, 255]

    int:
      maskmap_downfactor: 32

      nbr_keptfeat: 5

    bool:
      classification_from_allfeatures: True

      training_classifiers: True

      saving_classifiers:
        ridge: True

        logistic_regression: True

        random_forest: True



# Classifiers parameters

  classifierparam:
    ridge:
      # For more information on the parameters check sklearn.linear_model.RidgeClassifier documentation
      # #https://scikit-learn.org/stable/modules/linear_model.html
      alpha:  0.5

    logistic_regression:
      # For more information on the parameters check sklearn.linear_model.LogisticRegression documentation
      # #https://scikit-learn.org/stable/modules/linear_model.html
      solver: 'liblinear'

      multi_class: 'ovr'

    random_forest:
      # For more information on the parameters check sklearn.linear_model.RandomForestClassifier documentation
      # #https://scikit-learn.org/stable/modules/linear_model.html
      n_estimators: 100

      class_weight: 'balanced'












